variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - coverage
  - sonarqube-check

build:
  stage: build
  script:
    - cd IndividualPRJ/IndividualPrj
    - ./gradlew assemble

test:
  stage: test
  script:
    - cd IndividualPRJ/IndividualPrj
    - ./gradlew test

coverage:
  stage: coverage
  script:
    - cd IndividualPRJ/IndividualPrj
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - IndividualPRJ/IndividualPrj/build/reports/jacoco/test/html/

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd IndividualPRJ/IndividualPrj
    - ./gradlew sonarqube
  allow_failure: true